---
server:
  port: 8602
# =====================
# EUREKA NAMING SERVER
# =====================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: provider-service
  # ===============================
  # DATA SOURCE
  # ===============================
  datasource:
    ## default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    # ===============================
    # PostgreSQL DATABASE
    # ===============================
    # url: jdbc:postgresql://localhost:5432/hmfdb
    # username: postgres
    # password: T@lentHut2019
    # driverClassName: org.postgresql.Driver
    # url: jdbc:h2:mem:hmfdb

    # ===============================
    # H2 DATABASE
    # ===============================
    url: jdbc:h2:file:~/data/hmf/hmfdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    # H2 file database access from h2-console: jdbc:h2:file:~/data/hmf/hmfdb
  h2:
    console:
      path: /h2
      enabled: true
  #drop n create table again, good for testing, comment this in production
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      # properties:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      dbm2ddl:
        auto: true

